title: "Qusai Abed"
email: ""
description: "SOC Analyst | Cybersecurity"
url: "https://qusaiabed.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-archives

author:
  name: "Qusai Abed"
  avatar: "/assets/images/profile.jpg"
  bio: "SOC Analyst | Top 1% on THM"
  links:
    - label: "GitHub"
      url: "https://github.com/qusaiabed"
      icon: "fab fa-github"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/qusaiabed"
      icon: "fab fa-linkedin"

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

paginate: 10
paginate_path: "/page:num/"

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
